export const COMENZAR_AUTENTICACION = 'COMENZAR_AUTENTICACION';
export const EXITO_AUTENTICACION = 'EXITO_AUTENTICACION';
export const ERROR_AUTENTICACION = 'ERROR_AUTENTICACION';

export const COMENZAR_DESCARGA_LAPTOPS = 'COMENZAR_DESCARGA_LAPTOPS';
export const DESCARGA_LAPTOPS_EXITO = 'DESCARGA_LAPTOPS_EXITO';
export const DESCARGA_LAPTOPS_ERROR = 'DESCARGA_LAPTOPS_ERROR';

export const AGREGAR_LAPTOP = 'AGREGAR_LAPTOP';
export const AGREGAR_LAPTOP_EXITO = 'AGREGAR_LAPTOP_EXITO';
export const AGREGAR_LAPTOP_ERROR = 'AGREGAR_LAPTOP_ERROR';